version: "3"
services:
  jekyll:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      - JEKYLL_ENV=development
      - LANG=C.UTF-8
    command: serve --incremental --livereload --host 0.0.0.0
