[Settings]
  ID = "pslbc"

[build]
  base    = "."
  publish = "_site"
  command = "jekyll build"

[context.production]
  environment = { JEKYLL_ENV = "production" }

[[redirects]]
  from = "https://pslbc.netlify.com/*"
  to = "https://pslb.club/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
[headers.values]
  Content-Security-Policy = "default-src 'none'; object-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'self' https://code.jquery.com; img-src 'self'; font-src 'self'; connect-src 'self';"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"
